version: '3'
services:
  client:
    container_name: react-clientside
    build:
      context: ./
      dockerfile: Dockerfile-react
    ports:
      - "3000:3000"
  server:
    container_name: springboot-serverside
    depends_on:
      - db
    env_file:
      - 'variables.env'
    environment:
      MYSQL_HOST: db
    build:
      context: ./
      dockerfile: Dockerfile-spring
    links:
      - "db:database"
    ports:
      - "8080:8080"
  db:
    container_name: db
    image: mysql:8.0.17
    ports:
      - "3306:3306" 
    env_file:
      - 'variables.env'
    environment:
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_DATABASE: healthmonitor